package com.mint.cms.api;

public class Constants {
    public static final String THIRD_SOURCE_WEIXIN_APP = "weixinApp";
    public static final int URL_HTTP = 1;
    public static final int URL_HTTPS = 0;
    public static final int USER_OVER_TIME = 20;
    public static final String API_PLACEHOLDER_IMAGE_BEGIN = "_img_start_";
    public static final String API_PLACEHOLDER_IMAGE_END = "_img_end_";
    public static final String API_PLACEHOLDER_LINK_BEGIN = "_link_start_";
    public static final String API_PLACEHOLDER_LINK_END = "_link_end_";
    public static final String API_STATUS_SUCCESS = "\"true\"";
    public static final String G_API_STATUS_SUCCESS = "true";
    public static final String API_STATUS_FAIL = "\"false\"";
    public static final String G_API_STATUS_FAIL = "false";
    public static final String API_MESSAGE_FAIL = "\"system exception\"";
    public static final String API_MESSAGE_SUCCESS = "\"success\"";
    public static final String G_API_MESSAGE_SUCCESS = "success";
    public static final String API_MESSAGE_PARAM_REQUIRED = "\"param required\"";
    public static final String G_API_MESSAGE_PARAM_REQUIRED = "param required";
    public static final String API_MESSAGE_PARAM_ERROR = "\"param error\"";
    public static final String G_API_MESSAGE_PARAM_ERROR = "param error";
    public static final String API_MESSAGE_APP_PARAM_ERROR = "\"appId not exist or appId disabled\"";
    public static final String API_MESSAGE_SIGN_VALIDATE_ERROR = "\"sign validate error\"";
    public static final String API_MESSAGE_USER_NOT_FOUND = "\"user not found\"";
    public static final String API_MESSAGE_TOPIC_NOT_FOUND = "\"topic not found\"";
    public static final String API_MESSAGE_DELETE_ERROR = "\"delete error\"";
    public static final String API_MESSAGE_USER_NOT_LOGIN = "\"user not login\"";
    public static final String API_MESSAGE_PASSWORD_ERROR = "\"password error\"";
    public static final String API_MESSAGE_USERNAME_OR_PASSWORD_ERROR = "\"username or password error\"";
    public static final String API_MESSAGE_EAMILL_EXIST = "\"email exist\"";
    public static final String API_MESSAGE_USERNAME_EXIST = "\"username exist\"";
    public static final String API_MESSAGE_APPID_EXIST = "\"appid exist\"";
    public static final String API_MESSAGE_ORIGIN_PWD_ERROR = "\"origin password invalid\"";
    public static final String API_MESSAGE_UPLOAD_ERROR = "\"upload file error!\"";
    public static final String API_MESSAGE_REQUEST_REPEAT = "\"request api repeat\"";
    public static final String API_MESSAGE_USER_NOT_HAS_PERM = "\"user has not perm\"";
    public static final String API_MESSAGE_USER_OVER_TIME = "\"user over time\"";
    public static final String API_MESSAGE_OBJECT_NOT_FOUND = "\"object not found\"";
    public static final String API_MESSAGE_DEL_FAIL = "\"delete fail\"";
    public static final String API_MESSAGE_NOT_SUPPORT_UPLOAD_TYPE = "\"not support uploadType\"";
    public static final String API_MESSAGE_FILENAME_CONTAIN_ILLEGALCHAR = "\"fileName contain illegalchar\"";
    public static final String API_MESSAGE_IMAFILE_NOT_SUPPORT_EXT = "\"imafile not support ext\"";
    public static final String API_MESSAGE_NOT_PERMS_READ = "\"not perms reading\"";
    public static final String API_MESSAGE_PATH_REPEATE = "\"path not repeate\"";
    public static final String API_MESSAGE_INVALID_RECIPIENT_USER = "\"Invalid recipient user or user not exist\"";
    public static final String API_MESSAGE_EXPORT_TEMPLATE_FAIL = "\"export template faill\"";
    public static final String API_ARRAY_SPLIT_STR = ",";
    public static final String API_LIST_SPLIT_STR = ";";
}

